nubuilder/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^contact/', 'users.views.contact', name='contact'),
    url(r'^', include('nupages.urls', namespace='nupages')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nubuilder/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w\-_]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

nubuilder/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username

nubuilder/users/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

nubuilder/users/views.py
# -*- coding: utf-8 -*-
# Import the reverse lookup function
from django.core.urlresolvers import reverse

# view imports
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.views.generic import ListView

# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin

# Import the form from users/forms.py
from .forms import UserForm

# Import the customized User model
from .models import User


from django.shortcuts import render, render_to_response
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.mail import mail_admins, send_mail
from django.contrib import messages
from django.contrib.sites.models import Site
from django.conf import settings
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404, HttpResponse


@csrf_protect
def contact(request):
    if request.POST:
        post = request.POST
        first_name = post.get('first_name')
        last_name = post.get('last_name')
        phone = post.get('phone')
        email = post.get('email')
        _message = post.get('message')
        message = 'first_name: {}, last_name: {}, phone: {} email: {}, message: {}'.format(
            first_name, last_name, phone, email, _message)
        subject = unicode('Submission from {} {}').format(first_name, last_name)
        mail_admins(subject, message)
        _next = post.get('next', '/pages/')
        messages.success(request, 'Thanks for the submission!')
        return HttpResponseRedirect(_next)

    _next = request.GET.get('next', '')

    context = {'next': _next}
    return render_to_response('nupages/tenants/2/home.html',
        context,
        context_instance=RequestContext(request))

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
            kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                    kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

nubuilder/templates/avatar/add.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

nubuilder/templates/avatar/avatar_tag.html
<img src="{{ url }}" width="{{ size }}" height="{{ size }}" class="img-thumbnail">

nubuilder/templates/avatar/base.html
{% extends "base.html" %}

{% block title %}django-avatar{% endblock %}
{% block content %}{% endblock %}

nubuilder/templates/avatar/change.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% else %}
            <form method="POST" action="{% url 'avatar_change' %}">
                <ul>
                    {{ primary_avatar_form.as_ul }}
                </ul>
                <p>{% csrf_token %}<input type="submit" value="{% trans "Choose new Default" %}" /></p>
            </form>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

nubuilder/templates/nupages/tenants/2/base.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}Jackson Tile & Design{% endblock title %}
{% block description %}Jackson Tile & Design a family-owned professional tile and wood specialist with over 25 years of experience servicing Tucson and surrounding areas{% endblock description %}
{% block author %}Zacharia Lorenz{% endblock author %}

{% block ogtitle %}Jackson Tile & Design{% endblock ogtitle %}
{% block ogdesc %}Jackson Tile & Design a family-owned professional tile and wood specialist with over 25 years of experience servicing Tucson and surrounding areas{% endblock ogdesc %}
{% block ogimage %}{% static 'images/2/jackson-tile-design.jpg' %}{% endblock ogimage %}

{% block css %}
  <!-- Font Awesome-->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <!-- Import Flaticon Icons -->
  <link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">
  <!-- Minified Theme Styles from Bootstrap Builder-->
  <link rel="stylesheet" href="{% static 'css/jackson-tile.min.css' %}">

  <!-- Google Analytics-->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-58718929-1', 'auto');
    ga('send', 'pageview');
  </script>
{% endblock css %}

{% block navbar %}
  <!-- DEFAULT NAVBAR
  ================================================== -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button><!--/ .navbar-toggle-->
          <a class="navbar-brand" href="{% url 'nupages:detail' 'home' %}" title="Jackson Tile & Design | Homepage">Jackson Tile & Design</a>
        </div><!--/ .navbar-header-->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'nupages:detail' 'home' %}" title="Jackson Tile & Design | Homepage">Home</a></li>
            <li><a href="{% url 'nupages:detail' 'about' %}" title="About Us | Jackson Tile & Design">About</a></li>
            <li><a href="{% url 'nupages:detail' 'services' %}" title="Our Services | Jackson Tile & Design">Services</a></li>
            <li><a href="{% url 'nupages:detail' 'gallery' %}" title="Photo Gallery | Jackson Tile & Design">Gallery</a></li>
          </ul><!--/ .nav-->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  <!-- END DEFAULT NAVBAR
  ================================================== -->
{% endblock navbar %}

{% block content %}
{% endblock content %}

{% block footer %}
  <!-- FOOTER WIDGETS SECTION
  ================================================== -->
    <section class="footer-widgets bg-primary">
      <div class="container">
        <div class="row">
          <div class="widget col-md-4 col-md-offset-1">
            <h4 class="title">Contact Us</h4>
            <hr><!--/ .separator-->
            <h4>Jackson Tile & Design</h4>
            <p>29790 E. Hemlock Dr.<br>
              Marana, AZ 85658</p>
            <p><a href="mailto:jacksontile@gmail.com" title="Send an email to Jackson Tile & Design">jacksontile@gmail.com</a><br>
              <a href="tel:5202488966" title="Call Jackson Tile & Design">(520) 248-8966</a></p>
            <div class="social-icons">
              <a href="https://www.facebook.com/jacksontileanddesign" target="_blank" title="Facebook Page for Jackson Tile & Design"><i class="fa fa-facebook"></i></a>
              <a href="https://plus.google.com/114069048791019059655" target="_blank" title="Google+ Business Profile for Jackson Tile & Design"><i class="fa fa-google-plus"></i></a>
            </div><!--/ .social-icons-->
          </div><!--/ .widget-->
          <div class="widget col-md-4 col-md-offset-1">
            <h4 class="title">Signup to Stay Informed!</h4>
            <hr><!--/ .saparator-->
            <p>With our monthly newsletter you'll receive regular updates on industry news and all of our seasonal promotions. Rest assured... we never spam, we never share your info, and you can unsubscribe at any time.</p>
            <!-- - - - CONSTANT CONTACT FORM - - - -->
            <form method="post" action="https://www.formstack.com/forms/index.php" id="fsForm1867449">
              <input type="hidden" name="form" value="1867449">
              <input type="hidden" name="viewkey" value="8yNcCY0F1x">
              <input type="hidden" name="_submit" value="1">
              <div class="form-group">
                <input type="text" id="field28554111" name="field28554111" size="50" value="" required="required" aria-required="true" class="form-control input-lg" placeholder="First Name*">
              </div><!--/ .form-group-->
              <div class="form-group">
                <input type="email" id="field28554110" name="field28554110" size="50" required="required" aria-required="true" class="form-control input-lg" placeholder="Email Address*">
              </div><!--/ .form-group-->
              <div class="form-group">
                <input id="fsSubmitButton1867449" class="btn btn-success btn-lg btn-block" type="submit" value="Subscribe">
              </div><!--/ .form-group-->
            </form>
            <!-- - - -/ CONSTANT CONTACT FORM - - - -->
          </div><!--/ .widget-->
        </div><!--/ .row-->
      </div><!--/ .container-->
    </section>
  <!-- END FOOTER WIDGETS SECTION
  ================================================== -->

  <!-- COPYRIGHT FOOTER SECTION
  ================================================== -->
    <section class="copyright-footer bg-primary-dark">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <p class="copyright">2015 &copy; Jackson Tile & Design</p>
          </div><!--/ .copyright-->
          <div class="col-sm-6">
            <p class="developer">Developed by <a href="http://rabbit-hole-studios.com" target="_blank" title="Web Developer: Rabbit Hole Studio">Rabbit Hole Studio</a></p>
          </div><!--/ .developer-->
        </div><!--/ .row-->
      </div><!--/ .container-->
    </section>
  <!-- END COPYRIGHT FOOTER SECTION
  ================================================== -->
{% endblock footer %}

nubuilder/templates/nupages/tenants/2/gallery.html
{% extends "nupages/tenants/2/base.html" %}
{% load staticfiles i18n %}

{% block title %}Photo Gallery | Jackson Tile & Design{% endblock title %}
{% block description %}Take a look at our portfolio- with detailed photos of our tile, wood and laminate design installations{% endblock description %}

{% block content %}
  <!-- Pinterest Hover Button -->
  <script type="text/javascript" async defer  data-pin-color="white" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
  
  <!-- MASONRY GALLERY
  ================================================== -->
    <section class="masonry-gallery">
      <div class="container">
        <div class="row">
          <div class="section-header col-xs-12">
            <h2 class="section-title"><span>Gallery</span></h2>
          </div><!--/ .section-header-->
        </div><!--/ .row-->
      </div><!--/ .container-->
      <div role="tabpanel">
        <!------ GALLERY NAVIGATION ------>
        <div class="container hidden-xs">
          <div class="row gallery-nav">
            <ul class="filters" role="tablist">
              <li role="presentation" class="col-sm-3 active"><a href="#all" class="btn-filter" aria-controls="all" title="View all photos" role="tab" data-toggle="tab">All</a></li>
              <li role="presentation" class="col-sm-3"><a href="#tile" class="btn-filter" aria-controls="tile" title="Filter tile photos" role="tab" data-toggle="tab">Tile</a></li>
              <li role="presentation" class="col-sm-3"><a href="#wood" class="btn-filter" aria-controls="wood" title="Filter wood photos" role="tab" data-toggle="tab">Wood</a></li>
              <li role="presentation" class="col-sm-3"><a href="#laminate" class="btn-filter" aria-controls="laminate" title="Filter laminate photos" role="tab" data-toggle="tab">Laminate</a></li>
            </ul><!--/ .filters-->
          </div><!--/ .row-->
        </div><!--/ .container-->
        <!------ MOBILE GALLERY NAVBAR ------>
        <nav class="navbar navbar-default navbar-fixed-bottom navbar-gallery visible-xs" role="navigation">
          <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li role="presentation" class="active"><a href="#all" aria-controls="all" title="View all photos" role="tab" data-toggle="tab">
                <i class="nav-icon fa fa-eye" style="font-size:30px;"></i>
              </a></li>
              <li role="presentation"><a href="#tile" aria-controls="tile" title="Filter tile photos" role="tab" data-toggle="tab">
                <i class="nav-icon flaticon-tile2" style="font-size:45px; line-height:36px;"></i>
              </a></li>
              <li role="presentation"><a href="#wood" aria-controls="wood" title="Filter wood photos" role="tab" data-toggle="tab">
                <i class="nav-icon flaticon-wood2"></i>
              </a></li>
              <li role="presentation"><a href="#laminate" aria-controls="laminate" title="Filter laminate photos" role="tab" data-toggle="tab">
                <i class="nav-icon flaticon-laminate1"></i>
              </a></li>
            </ul><!-- /.nav -->
          </div><!-- /.container-fluid -->
        </nav><!-- /.navbar-menus -->
        <div class="container-fluid">
          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="all">
              <div class="row">
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor-exterior.jpg' %}" title="Tile patio">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-wall.jpg' %}" title="Mosaic tile design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower2.jpg' %}" title="Thick glass tile shower">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-sink.jpg' %}" title="Bathroom sink gray tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-stairs2.jpg' %}" title="Dark wood staircase">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower3.jpg' %}" title="Tile shower design with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor3.jpg' %}" title="Living room tile floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-fireplace2.jpg' %}" title="Southwestern tile fireplace">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-stairs.jpg' %}" title="Dark wood staircase">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kitchen-sink.jpg' %}" title="Kitchen sink tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-fireplace.jpg' %}" title="Contemporary tile fireplace">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-wall2.jpg' %}" title="Mosaic tile design on wall">
                  <img class="img-masonry" src="{% static 'images/2/gallery/laminate-wood-floor.jpg' %}" title="Laminate wood floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor2.jpg' %}" title="Dark wood floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor2.jpg' %}" title="Living room tile floor with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kachina2.jpg' %}" title="Tile Kachina floor design">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor.jpg' %}" title="Tile floor with doorframe accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor.jpg' %}" title="Light wood floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-sink2.jpg' %}" title="Bathroom sink multicolor tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor3.jpg' %}" title="Dark wood living room floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower.jpg' %}" title="Glass tile shower with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor4.jpg' %}" title="Diagonal tile floor design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kachina.jpg' %}" title="Tile Kachina design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-floor.jpg' %}" title="Entryway tile mandala design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/laminate-wood-floor2.jpg' %}" title="Laminate wood living room floor">
                </div><!--/ .col-masonry-->
              </div><!--/ .row-->
            </div><!--/ .tab-pane-->
            <div role="tabpanel" class="tab-pane fade" id="tile">
              <div class="row">
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor-exterior.jpg' %}" title="Tile patio">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-wall.jpg' %}" title="Mosaic tile design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower2.jpg' %}" title="Thick glass tile shower">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-sink.jpg' %}" title="Bathroom sink gray tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-floor.jpg' %}" title="Entryway tile mandala design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-fireplace2.jpg' %}" title="Southwestern tile fireplace">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kitchen-sink.jpg' %}" title="Kitchen sink tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-fireplace.jpg' %}" title="Contemporary tile fireplace">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-mosaic-wall2.jpg' %}" title="Mosaic tile design on wall">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor2.jpg' %}" title="Living room tile floor with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower3.jpg' %}" title="Tile shower design with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kachina2.jpg' %}" title="Tile Kachina floor design">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor.jpg' %}" title="Tile floor with doorframe accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-sink2.jpg' %}" title="Bathroom sink multicolor tile backsplash">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-shower.jpg' %}" title="Glass tile shower with accent">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor4.jpg' %}" title="Diagonal tile floor design">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-floor3.jpg' %}" title="Living room tile floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/tile-kachina.jpg' %}" title="Tile Kachina design">
                </div><!--/ .col-masonry-->
              </div><!--/ .row-->
            </div><!--/ .tab-pane-->
            <div role="tabpanel" class="tab-pane fade" id="wood">
              <div class="row">
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor3.jpg' %}" title="Dark wood living room floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-stairs2.jpg' %}" title="Dark wood staircase">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor2.jpg' %}" title="Dark wood floor">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-floor.jpg' %}" title="Light wood floor">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/wood-stairs.jpg' %}" title="Dark wood staircase">
                </div><!--/ .col-masonry-->
              </div><!--/ .row-->
            </div><!--/ .tab-pane-->
            <div role="tabpanel" class="tab-pane fade" id="laminate">
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/laminate-wood-floor.jpg' %}" title="Laminate wood floor">
                </div><!--/ .col-masonry-->
                <div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-masonry">
                  <img class="img-masonry" src="{% static 'images/2/gallery/laminate-wood-floor2.jpg' %}" title="Laminate wood living room floor">
                </div><!--/ .col-masonry-->
            </div><!--/ .tab-pane-->
          </div><!--/ .tab-content-->
        </div><!--/ .container-fluid-->
      </div><!--/ .tab-panel-->
    </section>
  <!-- END MASONRY GALLERY
  ================================================== -->

  <!-- CONSULTATION CTA
  ================================================== -->
    <section class="cta bg-secondary">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1 class="title">Contact us today for a free measurement and floor sampling!</h1>
          </div><!--/ .col-md-7-->
          <div class="col-md-4 col-md-offset-1 text-center">
            <a href="{% url 'nupages:detail' 'home' %}#consult" class="btn btn-lg btn-primary cta-btn" title="Request a free consultation with Jackson Tile & Design">Get a Consultation</a>
          </div><!--/ .col-md-4-->
        </div><!--/ .row-->
      </div><!--/ .container-->
    </section>
  <!-- END CONSULTATION CTA
  ================================================== -->
  {% endblock content %}

nubuilder/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->     
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <a class="btn btn-info" href="{% url 'avatar_change' %}">Avatar</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

nubuilder/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}